### ISSUE TITLE
Failed to convert a NumPy array to a Tensor (Unsupported object type float)

### ISSUE THREAD

**Issue by LePetitNewbie** [AubinMoreau/TennisBettingPrediction#1]
Hello Aubin
        Hope you are well. I was trying your project and ran into an error message and I was wondering if you could guide me towards a solution? (FYI I do not have any coding experience)  ...When I ran the code here:

 "model = trainModel(TrainX,TrainY,model)"

I get this message: 

Failed to convert a NumPy array to a Tensor (Unsupported object type float).

I did some checks and 'solution A' was to do this:
TrainX = np.asarray(TrainX).astype(np.float32)
TrainY = np.asarray(TrainY).astype(np.float32)

I did it and it worked for this part of the code. 

For the next part:

score = evaluateModel(TestX,TestY,model)   <---

On this line of code, I got the same error message for but for Test X - Test Y <-----

Failed to convert a NumPy array to a Tensor (Unsupported object type float).

I tried solution A with Test X and Test Y and it seemed to work. Like I mentioned, I do not have any experience with this and it started doing the test (its been 4 hours and it is still running this part of the code...is this Normal? should it be that long or did I just mess up something with solution A. Sorry for the long message about this. not sure how to explain it.

Hope you can help.

Ol

**Comment by AubinMoreau** [comment]
Hi ! 

If the code is running for hours it's because i created a loop that trains again if i'm not satisfied with the result of the training.

Delete the second part of this cell ...
![image](https://user-images.githubusercontent.com/25199792/117684413-4208c500-b1b5-11eb-92df-700f6396f08e.png)

to make it looks like this.
![image](https://user-images.githubusercontent.com/25199792/117684731-8d22d800-b1b5-11eb-99fc-042501a1da89.png)

If you have any other problem, be free to contact me again.

Have a nice day !

Aubin

**Comment by LePetitNewbie** [comment]
Hi Aubin
      Thanks for your reply. I removed the second part and it works now. :-) Appreciate your quick response and your work. 

Looking forward to your future project.

Take care (thanks again)
Ol

**Comment by AubinMoreau** [comment]
Hi,

I'm happy it worked !

Take care
